### ISSUE TITLE
Question: How to see plugin error inside docker container logs

### ISSUE THREAD

**Issue by Max-LAB** [Kong/kong-js-pdk#297]
Hi all, just a question from my side. I am running Kong with a custom js plugin in a Docker container. For some reason, Docker is failing to start, I only see this log output in my console. Side info, I am using RancherDesktop with nerdctl. 

```
kong-with-js-plugin |2023/04/12 16:47:15 [debug] 1#0: [lua] globalpatches.lua:306: randomseed(): seeding PRNG from OpenSSL RAND_bytes()
INFO[0002] Container "kong-with-js-plugin" exited       
INFO[0002] All the containers have exited               
INFO[0002] Stopping containers (forcibly)               
INFO[0002] Stopping container kong-with-js-plugin 
```

Any tips from your side on how can I debug what is actually failing in my plugin? It would be really helpful for my further development. 

I tested my setup with the small js plugin and it works, which confirms that my plugin paths are ok. Currently what I am trying to do is to build a `ts` plugin and compile it to `js` using `tsc`. So far worked. A problem occurred when I created an additional `ts` file with helper functions inside. Importing those functions inside my-plugin.ts brakes my setup. 

Here is how it looks like

```
/usr/local/kong/js-plugins/
  node_modules
  package.json
  my-plugin.js
  libs/
     helpers.ts
```

```js
# my-plugin.js
import { sayItOutloud } from "./lib/helpers";

async access(kong: any) {
  const test = new sayItOutloud();
  console.log(test.sayHello("Max"));
}
```

```js
# helpers.ts
export class sayItOutloud {
  sayHello(user) {
    return "Hello " + user + "!";
  }
}
```

Any tip would be appreciated! Thank you

**Comment by Max-LAB** [comment]
Ok I manage finally to output entire logs by doing `docker compose logs -f -t` on a separate console after the container crashes, and I saw this error: `Error: Cannot find module '/usr/local/kong/js-plugins/lib'`

Full log you can find in here:
```
kong-with-js-plugin |2023-04-13T09:40:31.786106542Z Error: Cannot find module '/usr/local/kong/js-plugins/lib'
kong-with-js-plugin |2023-04-13T09:40:31.786181542Z Require stack:
kong-with-js-plugin |2023-04-13T09:40:31.786240542Z - /usr/local/lib/node_modules/kong-pdk/server.js
kong-with-js-plugin |2023-04-13T09:40:31.786278542Z - /usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver
kong-with-js-plugin |2023-04-13T09:40:31.786381542Z     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
kong-with-js-plugin |2023-04-13T09:40:31.786783542Z     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/local/lib/node_modules/kong-pdk/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
kong-with-js-plugin |2023-04-13T09:40:31.786840542Z     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
kong-with-js-plugin |2023-04-13T09:40:31.786898542Z     at Server.loadPlugins (/usr/local/lib/node_modules/kong-pdk/server.js:66:33)
kong-with-js-plugin |2023-04-13T09:40:31.786946542Z     at new Server (/usr/local/lib/node_modules/kong-pdk/server.js:50:12)
kong-with-js-plugin |2023-04-13T09:40:31.786992542Z     at Object.<anonymous> (/usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver:18:12)
kong-with-js-plugin |2023-04-13T09:40:31.787029542Z     at Module._compile (node:internal/modules/cjs/loader:1254:14)
kong-with-js-plugin |2023-04-13T09:40:31.787078542Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
kong-with-js-plugin |2023-04-13T09:40:31.787127542Z     at Module.load (node:internal/modules/cjs/loader:1117:32)
kong-with-js-plugin |2023-04-13T09:40:31.787167542Z     at Function.Module._load (node:internal/modules/cjs/loader:958:12) {
kong-with-js-plugin |2023-04-13T09:40:31.787215542Z   code: 'MODULE_NOT_FOUND',
kong-with-js-plugin |2023-04-13T09:40:31.787253542Z   requireStack: [
kong-with-js-plugin |2023-04-13T09:40:31.787288542Z     '/usr/local/lib/node_modules/kong-pdk/server.js',
kong-with-js-plugin |2023-04-13T09:40:31.787325542Z     '/usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver'
kong-with-js-plugin |2023-04-13T09:40:31.787360542Z   ]
kong-with-js-plugin |2023-04-13T09:40:31.787560542Z }
kong-with-js-plugin |2023-04-13T09:40:31.798525542Z 2023/04/13 09:40:29 [error] 1#0: init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:150: Not a plugin info table:
kong-with-js-plugin |2023-04-13T09:40:31.798597542Z /usr/local/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
```
Why is a folder considered a module? And also, do you have any idea how could I decouple my code into multiple files like in the approach I took in my question?

**Comment by hanshuebner** [comment]
At this point, the JS plugin server only supports JavaScript and requires the specific directory layout described in the sample plugin.  We realize that this is restrictive, but we don't currently have plans to fix this ourselves, but you are welcome to send a pull request.
